server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    # show-sql: true
    properties: 
      hibernate: 
        lock: 
          timeout: 10000

employeeManagement:
  startupConfigs:
    thirdPartyApi: "https://dummyjson.com/users"
    apiKey: "usersCrudApi-12010"

management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
    health: 
      show-details: always
  health:
    circuitbreakers: 
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      legacy:
        enabled: true
      enabled: true
  timelimiter:
    metrics:
      enabled: true
    instances:
      apiLoaderLimiter:
        timeout-duration: 2s
        cancel-running-future: true


